sonar.projectKey=AEP-frontend
sonar.projectName=AEP Frontend
sonar.host.url=http://localhost:9000
sonar.token=sqp_db7ed2295da761ff29eaf5b1ddcbd8a403f5ea21

sonar.sources=app,components,lib,hooks,api
sonar.exclusions=**/node_modules/**,**/.next/**,**/dist/**